return {
  diablo_skull = {
    "9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP",
    " 9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP",
    "  `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'",
    "    `9XXXXXXXXXXXP' `9XX'   DIE    `98v8P'  HUMAN   `XXP' `9XXXXXXXXXXXP'",
    "        ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~",
    "                        )b.  .dbo.dP'`v'`9b.odb.  .dX(",
    "                      ,dXXXXXXXXXXXb     dXXXXXXXXXXXb.",
    "                     dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb",
    "                    dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb",
    "                    9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP",
    "                     `'      9XXXXXX(   )XXXXXXP      `'",
    "                              XXXX X.`v'.X XXXX",
    "                              XP^X'`b   d'`X^XX",
    "                              X. 9  `   '  P )X",
  },

  cutty_cat = {
    "",
    "",
    "",
    "",
    "",
    "  ⟋|､",
    " (°､ ｡ 7",
    " |､  ~ヽ",
    " じしf_,)〳",
  },

  dead_cutty_cat = {
    '          !:~~~ .:!M"T#$$$$WX??#MRRMMM!',
    '          ~?WuxiW*`   `"#$$$$8!!!!??!!!',
    '        :X- M$$$$       `"T#$T~!8$WUXU~',
    "       :%`  ~#$$$m:        ~!~ ?$$$$$$",
    '     :!`.-   ~T$$$$8xx.  .xWW- ~""##*"',
    "   -~~:<` !    ~?T#$$@@W@*?$$      /`",
    '!!! .!~~ !!     .:XUW$W!~ `"~:    :',
    ".:x%`!!  !H:   !WM$$$$Ti.: .!WUn+!`",
    '!!`:X~ .: ?H.!u "$$$B$$$!W:U!T$$M~',
    ' :X@!.-~   ?@WTWo("*$$$W$TH$! `    ⟋|､',
    'X$?!-~    : ?$$$B$Wu("**$RM!      (°､ ｡ 7',
    "~~ !     :   ~$$$$$B$$en:``       |､  ~ヽ",
    "W.~    :       ~##*$$$M~          じしf_,)〳",
  },

  pikachu = {
    "          ▀████▀▄▄              ▄█ ",
    "            █▀    ▀▀▄▄▄▄▄    ▄▄▀▀█ ",
    "    ▄        █          ▀▀▀▀▄  ▄▀  ",
    "   ▄▀ ▀▄      ▀▄              ▀▄▀  ",
    "  ▄▀    █     █▀   ▄█▀▄      ▄█    ",
    "  ▀▄     ▀▄  █     ▀██▀     ██▄█   ",
    "   ▀▄    ▄▀ █   ▄██▄   ▄  ▄  ▀▀ █  ",
    "    █  ▄▀  █    ▀██▀    ▀▀ ▀▀  ▄▀  ",
    "   █   █  █      ▄▄           ▄▀   ",
  },

  dog = {
    "                _,) ",
    "        _..._.-;-'  ",
    "     .-'     `(     ",
    "    /      ;   \\   ",
    "   ;.' ;`  ,;  ;    ",
    "  .'' ``. (  \\ ;   ",
    " / f_ _L \\ ;  )\\  ",
    " \\/|` '|\\/;; <;/  ",
    "((; \\_/  (()       ",
  },

  au5y = {
    "             ,ggg,              88888888888           ",
    '          dP""8I              88                     ',
    "         dP   88              88                     ",
    "        dP    88              88  ____               ",
    "       ,8'    88              88a8PPPP8b,            ",
    '       d88888888   gg      gg PP"     `8b  gg     gg ',
    ' __   ,8"     88   I8      8I          88  I8     8I ',
    'dP"  ,8P      Y8   I8,    ,8I          88  I8,   ,8I ',
    "Yb,_,dP       `8b,,d8b,  ,d8b,Y8a     a8P ,d8b, ,d8I ",
    ' "Y8P"         `Y88P\'"Y88P"`Y8 "Y88888P"  P""Y88P"888',
    "                                                ,d8I'",
    "                                              ,dP'8I ",
    '                                             ,8"  8I ',
    "                                             I8   8I ",
    "                                             `8, ,8I ",
    '                                              `Y8P" "',
  },

  au5yDog = {
    "             ,ggg,              88888888888           ",
    '          dP""8I              88                     ',
    "         dP   88              88                     ",
    "        dP    88              88  ____               ",
    "       ,8'    88              88a8PPPP8b,            ",
    '       d88888888   gg      gg PP"     `8b  gg     gg ',
    ' __   ,8"     88   I8      8I          88  I8     8I ',
    'dP"  ,8P      Y8   I8,    ,8I          88  I8,   ,8I ',
    "Yb,_,dP       `8b,,d8b,  ,d8b,Y8a     a8P ,d8b, ,d8I ",
    ' "Y8P"         `Y88P\'"Y88P"`Y8 "Y88888P"  P""Y88P"888',
    "                        _,)                     ,d8I'",
    "                _..._.-;-'                    ,dP'8I ",
    "             .-'     `(                      ,8\"  8I ",
    "            /      ;   \\                     I8   8I ",
    "           ;.' ;`  ,;  ;                     `8, ,8I ",
    "          .'' ``. (  \\ ;                     `Y8P\" \"",
    "         / f_ _L \\ ;  )\\  ",
    "         \\/|` '|\\/;; <;/  ",
    "        ((; \\_/  (()       ",
  },

  default = {
    " █████  ███████ ████████ ██████   ██████",
    "██   ██ ██         ██    ██   ██ ██    ██",
    "███████ ███████    ██    ██████  ██    ██",
    "██   ██      ██    ██    ██   ██ ██    ██",
    "██   ██ ███████    ██    ██   ██  ██████",
    " ",
    "    ███    ██ ██    ██ ██ ███    ███",
    "    ████   ██ ██    ██ ██ ████  ████",
    "    ██ ██  ██ ██    ██ ██ ██ ████ ██",
    "    ██  ██ ██  ██  ██  ██ ██  ██  ██",
    "    ██   ████   ████   ██ ██      ██",
  },
}
